# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b582bfe02e47c31d59f6631cf5d0361bcecdbc5a532ed4f0d19a4dbd0959c837e693b66d72eaf2e972dfa80e5e67523cdbd992524f291718c54672b8c2e82e7

test:
  secret_key_base: 8dc16813cad5d424a19f6500dad146ac87360ff8ccaff4538a7ea29177c7dada2a267bc46352c76ea58285de592c71c2092130f434460615d9a85be287988425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
